spring.application.name=cookEats
spring.datasource.url=jdbc:mysql://34.47.120.163:3306/cookeats?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=cookeats123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
